"""Page 4 — Glossary: definitions of technical terms used across the dashboard."""
import streamlit as st

st.title("Glossary")

st.markdown(
"Reference of technical terms used throughout this dashboard, "
"organized by category."
)

st.header("Clustering / Machine Learning")

st.markdown(
"**Cluster centroid** — Mean position of all points in a cluster; "
"represents the center of a hot-zone.\n\n"
"**Clustering** — Unsupervised technique that groups data points into subsets "
"(clusters) based on similarity, without predefined labels.\n\n"
"**DBSCAN** — Density-Based Spatial Clustering of Applications with "
"Noise. Groups closely packed points and marks outliers in "
"low-density regions.\n\n"
"**Density-based clustering** — Family of algorithms (e.g. DBSCAN) that "
"define clusters as high-density regions separated by low-density gaps, "
"without requiring a predefined number of clusters.\n\n"
"**Elbow method** — Technique to choose optimal *k* by finding the "
"inflection point on the inertia curve.\n\n"
"**eps (epsilon)** — DBSCAN parameter defining the maximum distance "
"between two points for them to be considered neighbors. Smaller "
"values require denser clusters.\n\n"
"**Feature** — An input variable used by a machine learning algorithm. "
"In this project, features are latitude and longitude coordinates.\n\n"
"**Geometric elbow detection** — Maximum-distance-to-diagonal method "
"that finds the point on the normalized inertia curve farthest from "
"the straight line connecting the first and last values. Used to "
"select the optimal k automatically.\n\n"
"**Hot-zone** — Geographic area with high Uber pickup density "
"where drivers should position themselves.\n\n"
"**k** — Number of clusters specified as input to KMeans. In this "
"project, k=11 was selected using the elbow method with geometric "
"elbow detection.\n\n"
"**k-distance plot** — A diagnostic chart for DBSCAN that plots the "
"distance to the k-th nearest neighbor for each point, sorted in "
"ascending order. A sharp elbow suggests a natural eps value.\n\n"
"**KMeans** — Partitioning algorithm that divides observations into "
"*k* clusters by minimizing the within-cluster sum of squares "
"(WCSS / inertia).\n\n"
"**min_samples** — DBSCAN parameter specifying the minimum number of "
"points required to form a dense region (core point). Higher values "
"produce fewer, denser clusters.\n\n"
"**Noise point** — In DBSCAN, a point that does not belong to any "
"cluster because it lies in a low-density region. Labeled -1.\n\n"
"**Partition-based clustering** — Family of algorithms (e.g. KMeans) "
"that divide the dataset into a fixed number of non-overlapping clusters "
"by optimizing a distance criterion.\n\n"
"**Silhouette score** — Metric measuring how similar a point is to "
"its own cluster versus neighboring clusters. Ranges from -1 to 1; "
"higher is better.\n\n"
"**Unsupervised learning** — Machine learning approach that finds "
"structure in data without labeled examples. Clustering is the main "
"unsupervised technique used in this project.\n\n"
"**WCSS / Inertia** — Within-Cluster Sum of Squares. Total distance "
"of points to their cluster center; lower means more compact "
"clusters."
)

st.header("Geographic / Spatial")

st.markdown(
"**Borough** — NYC administrative division: Manhattan, Brooklyn, "
"Queens, Bronx, Staten Island.\n\n"
"**Choropleth map** — A thematic map where geographic areas are shaded "
"in proportion to a measured variable. Used in the Hot Zone Explorer "
"to visualize pickup density by taxi zone.\n\n"
"**Cosine correction** — Adjustment for the distortion of longitude "
"at NYC's latitude (~40.7 N), where 1 degree of longitude does not "
"equal 1 degree of latitude in distance.\n\n"
"**GeoJSON** — A JSON-based format for encoding geographic features "
"(polygons, points, lines) with their properties. Used here to store "
"NYC taxi zone boundaries for map rendering.\n\n"
"**GPS** — Global Positioning System. Satellite-based system providing "
"latitude/longitude coordinates. The 2014 dataset consists of raw GPS "
"pickup coordinates.\n\n"
"**H3** — Uber's hexagonal hierarchical spatial indexing system used "
"in production.\n\n"
"**Haversine distance** — Formula for computing the great-circle "
"distance between two points on a sphere given their lat/lon "
"coordinates. Accounts for Earth's curvature.\n\n"
"**Hexagonal grid** — Spatial partitioning scheme that divides an area "
"into regular hexagons. Used by Uber's H3 system; hexagons have the "
"property that all 6 neighbors are equidistant from the center.\n\n"
"**OpenStreetMap** — Free, community-built map dataset used as the "
"base layer for the interactive maps in this dashboard.\n\n"
"**Shapefile** — A vector geospatial data format storing polygon or "
"point geometries. The NYC TLC taxi zone boundaries are provided as "
"a shapefile (.shp).\n\n"
"**Spatial join** — Operation matching GPS coordinates to the polygon "
"(zone) they fall within.\n\n"
"**Surge pricing** — Dynamic fare multiplier applied by Uber when "
"local demand exceeds supply. In Uber's H3 production system, surge "
"is computed per hexagonal cell.\n\n"
"**TLC taxi zone** — One of 263 geographic zones defined by the NYC "
"Taxi and Limousine Commission.\n\n"
"**WGS84** — World Geodetic System 1984. The standard coordinate "
"reference system (CRS) used for GPS and web mapping (EPSG:4326). "
"All spatial data in this project is reprojected to WGS84."
)

st.header("Data / Statistical")

st.markdown(
"**Calinski-Harabasz index** — Ratio of between-cluster variance to "
"within-cluster variance. Higher is better.\n\n"
"**Coefficient of variation (CV)** — Ratio of standard deviation to "
"mean, measuring relative dispersion. CV near 1.0 indicates high "
"variability across clusters.\n\n"
"**CSV** — Comma-Separated Values. Plain-text tabular data format used "
"for all input and output data files in this project.\n\n"
"**Dataset** — A structured collection of records. This project uses "
"two datasets: 4.5M GPS-level pickups from 2014, and pre-aggregated "
"zone-level counts from 2015.\n\n"
"**FOIL** — Freedom of Information Law. New York State law requiring "
"public agencies to make records available. The 2014 Uber pickup "
"dataset was obtained through a FOIL request to the NYC TLC.\n\n"
"**Heatmap** — A matrix visualization using color intensity to "
"represent values. Used to show pickup patterns across hours and "
"days of the week.\n\n"
"**LocationID** — Numeric identifier for a TLC taxi zone.\n\n"
"**Log scale (log10)** — A nonlinear scale where each step represents "
"a tenfold increase. Applied to the choropleth color axis to make "
"low-activity zones visible alongside high-activity ones.\n\n"
"**Outlier** — A data point that deviates significantly from the rest "
"of the distribution. In DBSCAN, outliers are labeled as noise "
"points.\n\n"
"**Parquet** — Columnar storage file format optimized for large-scale "
"data processing. More efficient than CSV for reading and filtering "
"large datasets.\n\n"
"**Pickup** — A recorded Uber ride start event with coordinates and "
"timestamp.\n\n"
"**Proportional distribution** — Expression of values as percentages "
"of a total, removing the effect of absolute volume differences. Used "
"for year-over-year temporal comparisons.\n\n"
"**Random sample** — A subset drawn uniformly at random from a "
"larger dataset. The 200,000-row sample used in cluster visualization "
"preserves the spatial distribution of the full 4.5M dataset.\n\n"
"**Rank change** — Difference in a zone's pickup rank between two "
"periods. Positive rank change means the zone rose in the ranking.\n\n"
"**Scatter map** — A map layer displaying individual data points at "
"their geographic coordinates, colored or sized by an attribute. "
"Used in the Methodology page to show cluster assignments.\n\n"
"**Year-over-year (YoY) growth** — Percentage change in a metric "
"between the same period in consecutive years. Calculated as "
"((value_new - value_old) / value_old) * 100."
)

st.header("Tools & Libraries")

st.markdown(
"**GeoPandas** — Python library extending pandas with support for "
"geometric operations (spatial joins, projections, polygon containment "
"tests) on geospatial data.\n\n"
"**MapLibre** — Open-source map rendering library used by Plotly for "
"interactive map visualizations. Successor to Mapbox GL JS.\n\n"
"**NumPy** — Python library for numerical computing. Used for array "
"operations including log transformations and coordinate processing.\n\n"
"**Pandas** — Python data manipulation library providing DataFrame "
"structures. Used for all tabular data loading, filtering, and "
"aggregation in this project.\n\n"
"**Plotly** — Python visualization library for interactive charts and "
"maps. All charts and choropleth maps in this dashboard are rendered "
"with Plotly Express or Plotly Graph Objects.\n\n"
"**Streamlit** — Python framework for building interactive data "
"applications from Python scripts. This dashboard is built with "
"Streamlit."
)
